language: cpp
sudo: required
dist: bionic
git:
  submodules: false
before_install:
  - git submodule update --init spec
os:
  - linux
compiler:
  - gcc
env:
  matrix:
  - LLVM_CONFIG=llvm-config-10 CLANG=clang-10

addons:
  apt:
    packages:
    - cmake
    - gcc-9
    - g++-9
script:
  - ./travis.sh

